common:
  version: @project.version@

server:
  port: 3000

spring:
  application:
    name: bookingapi
  datasource:
    url: jdbc:postgresql://localhost:5432/coding-challenge
    username: postgres
    password: mypassword123!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false # for debugging purposes we can show the sql statements, but for production or load tests better disabling it
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never # database is already populated
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: off # we can use trace locally to see the queries parameter values if necessary
    org.hibernate.SQL: info
